[package]
name = "tmdb"
version = "4.0.0"
edition = "2024"
authors = ["Ofer Sadan <ofersadan85@gmail.com>"]
description = "The Movie Database (TMDb) API for Rust"
documentation = "https://docs.rs/crate/tmdb"
homepage = "https://github.com/ofersadan85/tmdb-rs"
repository = "https://github.com/ofersadan85/tmdb-rs"
readme = "README.md"
license = "MIT"

# [lints.rust]
# unused_imports = "allow"
# dead_code = "allow"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["json", "query"] }
thiserror = "2.0.20"
# serde_json = "1.0.151"
async-trait = "0.1.92"
serde_repr = "0.1.21"
chrono = { version = "0.4.45", features = ["serde"] }

[dev-dependencies]
dotenvy = { version = "0.15.7" }
tokio = { version = "1.53.1", features = ["test-util", "macros", "rt-multi-thread"] }

[features]
default = []
