[package]
name = "tmdb"
version = "4.0.0"
edition = "2024"
authors = ["Ofer Sadan <ofersadan85@gmail.com>"]
description = "The Movie Database (TMDb) API for Rust"
documentation = "https://docs.rs/crate/tmdb"
homepage = "https://github.com/ofersadan85/tmdb-rs"
repository = "https://github.com/ofersadan85/tmdb-rs"
readme = "README.md"
license = "MIT"

# [lints.rust]
# unused_imports = "allow"
# dead_code = "allow"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

[dependencies]
dotenvy = "0.15.7"
serde = { version = "1.0.229", features = ["derive"] }
reqwest = { version = "0.13.4", features = ["json", "query"] }
thiserror = "2.0.20"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full"] }

[features]
default = ["reqwest/blocking"]  # TODO
blocking = ["reqwest/blocking"]
